// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/admin_tag.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/admin_tag.go -destination=internal/repo/mocks/admin_tag_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	repo "github.com/puddingtonnn/offlinemeetup_backend/internal/repo"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminTagRepository is a mock of AdminTagRepository interface.
type MockAdminTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminTagRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminTagRepositoryMockRecorder is the mock recorder for MockAdminTagRepository.
type MockAdminTagRepositoryMockRecorder struct {
	mock *MockAdminTagRepository
}

// NewMockAdminTagRepository creates a new mock instance.
func NewMockAdminTagRepository(ctrl *gomock.Controller) *MockAdminTagRepository {
	mock := &MockAdminTagRepository{ctrl: ctrl}
	mock.recorder = &MockAdminTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminTagRepository) EXPECT() *MockAdminTagRepositoryMockRecorder {
	return m.recorder
}

// CreateTx mocks base method.
func (m *MockAdminTagRepository) CreateTx(ctx context.Context, tx bun.IDB, name string) (*domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTx", ctx, tx, name)
	ret0, _ := ret[0].(*domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTx indicates an expected call of CreateTx.
func (mr *MockAdminTagRepositoryMockRecorder) CreateTx(ctx, tx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTx", reflect.TypeOf((*MockAdminTagRepository)(nil).CreateTx), ctx, tx, name)
}

// ListWithUsage mocks base method.
func (m *MockAdminTagRepository) ListWithUsage(ctx context.Context) ([]repo.TagUsage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithUsage", ctx)
	ret0, _ := ret[0].([]repo.TagUsage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithUsage indicates an expected call of ListWithUsage.
func (mr *MockAdminTagRepositoryMockRecorder) ListWithUsage(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithUsage", reflect.TypeOf((*MockAdminTagRepository)(nil).ListWithUsage), ctx)
}

// RenameTx mocks base method.
func (m *MockAdminTagRepository) RenameTx(ctx context.Context, tx bun.IDB, id int64, name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenameTx", ctx, tx, id, name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenameTx indicates an expected call of RenameTx.
func (mr *MockAdminTagRepositoryMockRecorder) RenameTx(ctx, tx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenameTx", reflect.TypeOf((*MockAdminTagRepository)(nil).RenameTx), ctx, tx, id, name)
}

// RunInTx mocks base method.
func (m *MockAdminTagRepository) RunInTx(ctx context.Context, fn func(bun.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockAdminTagRepositoryMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockAdminTagRepository)(nil).RunInTx), ctx, fn)
}

// SetHiddenTx mocks base method.
func (m *MockAdminTagRepository) SetHiddenTx(ctx context.Context, tx bun.IDB, id int64, hidden bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHiddenTx", ctx, tx, id, hidden)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHiddenTx indicates an expected call of SetHiddenTx.
func (mr *MockAdminTagRepositoryMockRecorder) SetHiddenTx(ctx, tx, id, hidden any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHiddenTx", reflect.TypeOf((*MockAdminTagRepository)(nil).SetHiddenTx), ctx, tx, id, hidden)
}

// MockadminTagCache is a mock of adminTagCache interface.
type MockadminTagCache struct {
	ctrl     *gomock.Controller
	recorder *MockadminTagCacheMockRecorder
	isgomock struct{}
}

// MockadminTagCacheMockRecorder is the mock recorder for MockadminTagCache.
type MockadminTagCacheMockRecorder struct {
	mock *MockadminTagCache
}

// NewMockadminTagCache creates a new mock instance.
func NewMockadminTagCache(ctrl *gomock.Controller) *MockadminTagCache {
	mock := &MockadminTagCache{ctrl: ctrl}
	mock.recorder = &MockadminTagCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminTagCache) EXPECT() *MockadminTagCacheMockRecorder {
	return m.recorder
}

// InvalidateTags mocks base method.
func (m *MockadminTagCache) InvalidateTags(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateTags", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateTags indicates an expected call of InvalidateTags.
func (mr *MockadminTagCacheMockRecorder) InvalidateTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateTags", reflect.TypeOf((*MockadminTagCache)(nil).InvalidateTags), ctx)
}
