// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/admin_user.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/admin_user.go -destination=internal/repo/mocks/admin_user_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	repo "github.com/puddingtonnn/offlinemeetup_backend/internal/repo"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminUserRepository is a mock of AdminUserRepository interface.
type MockAdminUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminUserRepositoryMockRecorder is the mock recorder for MockAdminUserRepository.
type MockAdminUserRepositoryMockRecorder struct {
	mock *MockAdminUserRepository
}

// NewMockAdminUserRepository creates a new mock instance.
func NewMockAdminUserRepository(ctrl *gomock.Controller) *MockAdminUserRepository {
	mock := &MockAdminUserRepository{ctrl: ctrl}
	mock.recorder = &MockAdminUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminUserRepository) EXPECT() *MockAdminUserRepositoryMockRecorder {
	return m.recorder
}

// GetDetail mocks base method.
func (m *MockAdminUserRepository) GetDetail(ctx context.Context, id int64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDetail", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDetail indicates an expected call of GetDetail.
func (mr *MockAdminUserRepositoryMockRecorder) GetDetail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDetail", reflect.TypeOf((*MockAdminUserRepository)(nil).GetDetail), ctx, id)
}

// List mocks base method.
func (m *MockAdminUserRepository) List(ctx context.Context, q repo.UserQuery) ([]domain.User, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockAdminUserRepositoryMockRecorder) List(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockAdminUserRepository)(nil).List), ctx, q)
}

// MeetupIDsForUser mocks base method.
func (m *MockAdminUserRepository) MeetupIDsForUser(ctx context.Context, userID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeetupIDsForUser", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeetupIDsForUser indicates an expected call of MeetupIDsForUser.
func (mr *MockAdminUserRepositoryMockRecorder) MeetupIDsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeetupIDsForUser", reflect.TypeOf((*MockAdminUserRepository)(nil).MeetupIDsForUser), ctx, userID)
}

// RunInTx mocks base method.
func (m *MockAdminUserRepository) RunInTx(ctx context.Context, fn func(bun.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockAdminUserRepositoryMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockAdminUserRepository)(nil).RunInTx), ctx, fn)
}

// SetStatusTx mocks base method.
func (m *MockAdminUserRepository) SetStatusTx(ctx context.Context, tx bun.IDB, userID int64, status domain.UserStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetStatusTx", ctx, tx, userID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatusTx indicates an expected call of SetStatusTx.
func (mr *MockAdminUserRepositoryMockRecorder) SetStatusTx(ctx, tx, userID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusTx", reflect.TypeOf((*MockAdminUserRepository)(nil).SetStatusTx), ctx, tx, userID, status)
}

// SoftDeleteTx mocks base method.
func (m *MockAdminUserRepository) SoftDeleteTx(ctx context.Context, tx bun.IDB, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteTx", ctx, tx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteTx indicates an expected call of SoftDeleteTx.
func (mr *MockAdminUserRepositoryMockRecorder) SoftDeleteTx(ctx, tx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteTx", reflect.TypeOf((*MockAdminUserRepository)(nil).SoftDeleteTx), ctx, tx, userID)
}

// MockRefreshTokenRevoker is a mock of RefreshTokenRevoker interface.
type MockRefreshTokenRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenRevokerMockRecorder
	isgomock struct{}
}

// MockRefreshTokenRevokerMockRecorder is the mock recorder for MockRefreshTokenRevoker.
type MockRefreshTokenRevokerMockRecorder struct {
	mock *MockRefreshTokenRevoker
}

// NewMockRefreshTokenRevoker creates a new mock instance.
func NewMockRefreshTokenRevoker(ctrl *gomock.Controller) *MockRefreshTokenRevoker {
	mock := &MockRefreshTokenRevoker{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshTokenRevoker) EXPECT() *MockRefreshTokenRevokerMockRecorder {
	return m.recorder
}

// RevokeAllForUser mocks base method.
func (m *MockRefreshTokenRevoker) RevokeAllForUser(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllForUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllForUser indicates an expected call of RevokeAllForUser.
func (mr *MockRefreshTokenRevokerMockRecorder) RevokeAllForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllForUser", reflect.TypeOf((*MockRefreshTokenRevoker)(nil).RevokeAllForUser), ctx, userID)
}

// MockadminProfileCache is a mock of adminProfileCache interface.
type MockadminProfileCache struct {
	ctrl     *gomock.Controller
	recorder *MockadminProfileCacheMockRecorder
	isgomock struct{}
}

// MockadminProfileCacheMockRecorder is the mock recorder for MockadminProfileCache.
type MockadminProfileCacheMockRecorder struct {
	mock *MockadminProfileCache
}

// NewMockadminProfileCache creates a new mock instance.
func NewMockadminProfileCache(ctrl *gomock.Controller) *MockadminProfileCache {
	mock := &MockadminProfileCache{ctrl: ctrl}
	mock.recorder = &MockadminProfileCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminProfileCache) EXPECT() *MockadminProfileCacheMockRecorder {
	return m.recorder
}

// InvalidateProfile mocks base method.
func (m *MockadminProfileCache) InvalidateProfile(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateProfile", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateProfile indicates an expected call of InvalidateProfile.
func (mr *MockadminProfileCacheMockRecorder) InvalidateProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateProfile", reflect.TypeOf((*MockadminProfileCache)(nil).InvalidateProfile), ctx, userID)
}

// MockadminMeetupCache is a mock of adminMeetupCache interface.
type MockadminMeetupCache struct {
	ctrl     *gomock.Controller
	recorder *MockadminMeetupCacheMockRecorder
	isgomock struct{}
}

// MockadminMeetupCacheMockRecorder is the mock recorder for MockadminMeetupCache.
type MockadminMeetupCacheMockRecorder struct {
	mock *MockadminMeetupCache
}

// NewMockadminMeetupCache creates a new mock instance.
func NewMockadminMeetupCache(ctrl *gomock.Controller) *MockadminMeetupCache {
	mock := &MockadminMeetupCache{ctrl: ctrl}
	mock.recorder = &MockadminMeetupCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminMeetupCache) EXPECT() *MockadminMeetupCacheMockRecorder {
	return m.recorder
}

// InvalidateMeetup mocks base method.
func (m *MockadminMeetupCache) InvalidateMeetup(ctx context.Context, meetupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateMeetup", ctx, meetupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateMeetup indicates an expected call of InvalidateMeetup.
func (mr *MockadminMeetupCacheMockRecorder) InvalidateMeetup(ctx, meetupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateMeetup", reflect.TypeOf((*MockadminMeetupCache)(nil).InvalidateMeetup), ctx, meetupID)
}
