// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/admin_auth.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/admin_auth.go -destination=internal/repo/mocks/admin_auth_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/puddingtonnn/offlinemeetup_backend/internal/cache"
	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminRepository is a mock of AdminRepository interface.
type MockAdminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminRepositoryMockRecorder is the mock recorder for MockAdminRepository.
type MockAdminRepositoryMockRecorder struct {
	mock *MockAdminRepository
}

// NewMockAdminRepository creates a new mock instance.
func NewMockAdminRepository(ctrl *gomock.Controller) *MockAdminRepository {
	mock := &MockAdminRepository{ctrl: ctrl}
	mock.recorder = &MockAdminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepository) EXPECT() *MockAdminRepositoryMockRecorder {
	return m.recorder
}

// GetByEmail mocks base method.
func (m *MockAdminRepository) GetByEmail(ctx context.Context, email string) (*domain.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*domain.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockAdminRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockAdminRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockAdminRepository) GetByID(ctx context.Context, id int64) (*domain.AdminUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.AdminUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdminRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdminRepository)(nil).GetByID), ctx, id)
}

// MockAdminSessionStore is a mock of AdminSessionStore interface.
type MockAdminSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockAdminSessionStoreMockRecorder
	isgomock struct{}
}

// MockAdminSessionStoreMockRecorder is the mock recorder for MockAdminSessionStore.
type MockAdminSessionStoreMockRecorder struct {
	mock *MockAdminSessionStore
}

// NewMockAdminSessionStore creates a new mock instance.
func NewMockAdminSessionStore(ctrl *gomock.Controller) *MockAdminSessionStore {
	mock := &MockAdminSessionStore{ctrl: ctrl}
	mock.recorder = &MockAdminSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminSessionStore) EXPECT() *MockAdminSessionStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAdminSessionStore) Delete(ctx context.Context, tokenHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tokenHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdminSessionStoreMockRecorder) Delete(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdminSessionStore)(nil).Delete), ctx, tokenHash)
}

// Get mocks base method.
func (m *MockAdminSessionStore) Get(ctx context.Context, tokenHash string) (cache.AdminSession, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, tokenHash)
	ret0, _ := ret[0].(cache.AdminSession)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockAdminSessionStoreMockRecorder) Get(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdminSessionStore)(nil).Get), ctx, tokenHash)
}

// Save mocks base method.
func (m *MockAdminSessionStore) Save(ctx context.Context, tokenHash string, sess cache.AdminSession, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, tokenHash, sess, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockAdminSessionStoreMockRecorder) Save(ctx, tokenHash, sess, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockAdminSessionStore)(nil).Save), ctx, tokenHash, sess, ttl)
}

// Touch mocks base method.
func (m *MockAdminSessionStore) Touch(ctx context.Context, tokenHash string, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, tokenHash, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockAdminSessionStoreMockRecorder) Touch(ctx, tokenHash, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockAdminSessionStore)(nil).Touch), ctx, tokenHash, ttl)
}
