// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/admin_meetup.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/admin_meetup.go -destination=internal/repo/mocks/admin_meetup_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	dto "github.com/puddingtonnn/offlinemeetup_backend/internal/dto"
	repo "github.com/puddingtonnn/offlinemeetup_backend/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminMeetupRepository is a mock of AdminMeetupRepository interface.
type MockAdminMeetupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdminMeetupRepositoryMockRecorder
	isgomock struct{}
}

// MockAdminMeetupRepositoryMockRecorder is the mock recorder for MockAdminMeetupRepository.
type MockAdminMeetupRepositoryMockRecorder struct {
	mock *MockAdminMeetupRepository
}

// NewMockAdminMeetupRepository creates a new mock instance.
func NewMockAdminMeetupRepository(ctrl *gomock.Controller) *MockAdminMeetupRepository {
	mock := &MockAdminMeetupRepository{ctrl: ctrl}
	mock.recorder = &MockAdminMeetupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminMeetupRepository) EXPECT() *MockAdminMeetupRepositoryMockRecorder {
	return m.recorder
}

// AdminList mocks base method.
func (m *MockAdminMeetupRepository) AdminList(ctx context.Context, q repo.MeetupAdminQuery) ([]domain.Meetup, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminList", ctx, q)
	ret0, _ := ret[0].([]domain.Meetup)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AdminList indicates an expected call of AdminList.
func (mr *MockAdminMeetupRepositoryMockRecorder) AdminList(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminList", reflect.TypeOf((*MockAdminMeetupRepository)(nil).AdminList), ctx, q)
}

// GetByID mocks base method.
func (m *MockAdminMeetupRepository) GetByID(ctx context.Context, id, currentUserID int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, currentUserID)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdminMeetupRepositoryMockRecorder) GetByID(ctx, id, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdminMeetupRepository)(nil).GetByID), ctx, id, currentUserID)
}

// MockOfficialMeetupWriter is a mock of OfficialMeetupWriter interface.
type MockOfficialMeetupWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOfficialMeetupWriterMockRecorder
	isgomock struct{}
}

// MockOfficialMeetupWriterMockRecorder is the mock recorder for MockOfficialMeetupWriter.
type MockOfficialMeetupWriterMockRecorder struct {
	mock *MockOfficialMeetupWriter
}

// NewMockOfficialMeetupWriter creates a new mock instance.
func NewMockOfficialMeetupWriter(ctrl *gomock.Controller) *MockOfficialMeetupWriter {
	mock := &MockOfficialMeetupWriter{ctrl: ctrl}
	mock.recorder = &MockOfficialMeetupWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfficialMeetupWriter) EXPECT() *MockOfficialMeetupWriterMockRecorder {
	return m.recorder
}

// CreateMeetup mocks base method.
func (m *MockOfficialMeetupWriter) CreateMeetup(ctx context.Context, userID int64, req dto.CreateMeetupRequest) (*dto.MeetupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMeetup", ctx, userID, req)
	ret0, _ := ret[0].(*dto.MeetupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMeetup indicates an expected call of CreateMeetup.
func (mr *MockOfficialMeetupWriterMockRecorder) CreateMeetup(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMeetup", reflect.TypeOf((*MockOfficialMeetupWriter)(nil).CreateMeetup), ctx, userID, req)
}

// UpdateMeetup mocks base method.
func (m *MockOfficialMeetupWriter) UpdateMeetup(ctx context.Context, userID, meetupID int64, req dto.UpdateMeetupRequest) (*dto.MeetupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeetup", ctx, userID, meetupID, req)
	ret0, _ := ret[0].(*dto.MeetupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMeetup indicates an expected call of UpdateMeetup.
func (mr *MockOfficialMeetupWriterMockRecorder) UpdateMeetup(ctx, userID, meetupID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeetup", reflect.TypeOf((*MockOfficialMeetupWriter)(nil).UpdateMeetup), ctx, userID, meetupID, req)
}
