// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/file_purge.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/file_purge.go -destination=internal/repo/mocks/file_purge_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	s3 "github.com/aws/aws-sdk-go-v2/service/s3"
	uuid "github.com/google/uuid"
	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockS3DeleteObjectAPI is a mock of S3DeleteObjectAPI interface.
type MockS3DeleteObjectAPI struct {
	ctrl     *gomock.Controller
	recorder *MockS3DeleteObjectAPIMockRecorder
	isgomock struct{}
}

// MockS3DeleteObjectAPIMockRecorder is the mock recorder for MockS3DeleteObjectAPI.
type MockS3DeleteObjectAPIMockRecorder struct {
	mock *MockS3DeleteObjectAPI
}

// NewMockS3DeleteObjectAPI creates a new mock instance.
func NewMockS3DeleteObjectAPI(ctrl *gomock.Controller) *MockS3DeleteObjectAPI {
	mock := &MockS3DeleteObjectAPI{ctrl: ctrl}
	mock.recorder = &MockS3DeleteObjectAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3DeleteObjectAPI) EXPECT() *MockS3DeleteObjectAPIMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockS3DeleteObjectAPI) DeleteObject(ctx context.Context, params *s3.DeleteObjectInput, optFns ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range optFns {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteObject", varargs...)
	ret0, _ := ret[0].(*s3.DeleteObjectOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockS3DeleteObjectAPIMockRecorder) DeleteObject(ctx, params any, optFns ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, optFns...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockS3DeleteObjectAPI)(nil).DeleteObject), varargs...)
}

// MockFileStore is a mock of FileStore interface.
type MockFileStore struct {
	ctrl     *gomock.Controller
	recorder *MockFileStoreMockRecorder
	isgomock struct{}
}

// MockFileStoreMockRecorder is the mock recorder for MockFileStore.
type MockFileStoreMockRecorder struct {
	mock *MockFileStore
}

// NewMockFileStore creates a new mock instance.
func NewMockFileStore(ctrl *gomock.Controller) *MockFileStore {
	mock := &MockFileStore{ctrl: ctrl}
	mock.recorder = &MockFileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileStore) EXPECT() *MockFileStoreMockRecorder {
	return m.recorder
}

// DeleteTx mocks base method.
func (m *MockFileStore) DeleteTx(ctx context.Context, tx bun.IDB, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTx", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockFileStoreMockRecorder) DeleteTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockFileStore)(nil).DeleteTx), ctx, tx, id)
}

// GetByID mocks base method.
func (m *MockFileStore) GetByID(ctx context.Context, id uuid.UUID) (*domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockFileStoreMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockFileStore)(nil).GetByID), ctx, id)
}
