// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/file_gc.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/file_gc.go -destination=internal/repo/mocks/file_gc_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockOrphanFileStore is a mock of OrphanFileStore interface.
type MockOrphanFileStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrphanFileStoreMockRecorder
	isgomock struct{}
}

// MockOrphanFileStoreMockRecorder is the mock recorder for MockOrphanFileStore.
type MockOrphanFileStoreMockRecorder struct {
	mock *MockOrphanFileStore
}

// NewMockOrphanFileStore creates a new mock instance.
func NewMockOrphanFileStore(ctrl *gomock.Controller) *MockOrphanFileStore {
	mock := &MockOrphanFileStore{ctrl: ctrl}
	mock.recorder = &MockOrphanFileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrphanFileStore) EXPECT() *MockOrphanFileStoreMockRecorder {
	return m.recorder
}

// DeleteTx mocks base method.
func (m *MockOrphanFileStore) DeleteTx(ctx context.Context, tx bun.IDB, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTx", ctx, tx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTx indicates an expected call of DeleteTx.
func (mr *MockOrphanFileStoreMockRecorder) DeleteTx(ctx, tx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTx", reflect.TypeOf((*MockOrphanFileStore)(nil).DeleteTx), ctx, tx, id)
}

// ListOrphans mocks base method.
func (m *MockOrphanFileStore) ListOrphans(ctx context.Context, minAge time.Duration, limit int) ([]domain.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrphans", ctx, minAge, limit)
	ret0, _ := ret[0].([]domain.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrphans indicates an expected call of ListOrphans.
func (mr *MockOrphanFileStoreMockRecorder) ListOrphans(ctx, minAge, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrphans", reflect.TypeOf((*MockOrphanFileStore)(nil).ListOrphans), ctx, minAge, limit)
}
