// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/meetup.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/meetup.go -destination=internal/repo/mocks/meetup_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	dto "github.com/puddingtonnn/offlinemeetup_backend/internal/dto"
	repo "github.com/puddingtonnn/offlinemeetup_backend/internal/repo"
	gomock "go.uber.org/mock/gomock"
)

// MockMeetupRepository is a mock of MeetupRepository interface.
type MockMeetupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMeetupRepositoryMockRecorder
	isgomock struct{}
}

// MockMeetupRepositoryMockRecorder is the mock recorder for MockMeetupRepository.
type MockMeetupRepositoryMockRecorder struct {
	mock *MockMeetupRepository
}

// NewMockMeetupRepository creates a new mock instance.
func NewMockMeetupRepository(ctrl *gomock.Controller) *MockMeetupRepository {
	mock := &MockMeetupRepository{ctrl: ctrl}
	mock.recorder = &MockMeetupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMeetupRepository) EXPECT() *MockMeetupRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMeetupRepository) Create(ctx context.Context, meetup *domain.Meetup, chat *domain.Chat, tagIDs []int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, meetup, chat, tagIDs)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockMeetupRepositoryMockRecorder) Create(ctx, meetup, chat, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMeetupRepository)(nil).Create), ctx, meetup, chat, tagIDs)
}

// Delete mocks base method.
func (m *MockMeetupRepository) Delete(ctx context.Context, id int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockMeetupRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockMeetupRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockMeetupRepository) GetByID(ctx context.Context, id, currentUserID int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, currentUserID)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockMeetupRepositoryMockRecorder) GetByID(ctx, id, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockMeetupRepository)(nil).GetByID), ctx, id, currentUserID)
}

// GetByInviteToken mocks base method.
func (m *MockMeetupRepository) GetByInviteToken(ctx context.Context, token uuid.UUID, currentUserID int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInviteToken", ctx, token, currentUserID)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInviteToken indicates an expected call of GetByInviteToken.
func (mr *MockMeetupRepositoryMockRecorder) GetByInviteToken(ctx, token, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInviteToken", reflect.TypeOf((*MockMeetupRepository)(nil).GetByInviteToken), ctx, token, currentUserID)
}

// GetForAuth mocks base method.
func (m *MockMeetupRepository) GetForAuth(ctx context.Context, id, userID int64) (*repo.MeetupAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForAuth", ctx, id, userID)
	ret0, _ := ret[0].(*repo.MeetupAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForAuth indicates an expected call of GetForAuth.
func (mr *MockMeetupRepositoryMockRecorder) GetForAuth(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForAuth", reflect.TypeOf((*MockMeetupRepository)(nil).GetForAuth), ctx, id, userID)
}

// Join mocks base method.
func (m *MockMeetupRepository) Join(ctx context.Context, meetupID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Join", ctx, meetupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockMeetupRepositoryMockRecorder) Join(ctx, meetupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockMeetupRepository)(nil).Join), ctx, meetupID, userID)
}

// Leave mocks base method.
func (m *MockMeetupRepository) Leave(ctx context.Context, meetupID, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leave", ctx, meetupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Leave indicates an expected call of Leave.
func (mr *MockMeetupRepositoryMockRecorder) Leave(ctx, meetupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leave", reflect.TypeOf((*MockMeetupRepository)(nil).Leave), ctx, meetupID, userID)
}

// List mocks base method.
func (m *MockMeetupRepository) List(ctx context.Context, filter repo.MeetupQuery, currentUserID int64) ([]domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, currentUserID)
	ret0, _ := ret[0].([]domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockMeetupRepositoryMockRecorder) List(ctx, filter, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockMeetupRepository)(nil).List), ctx, filter, currentUserID)
}

// Update mocks base method.
func (m *MockMeetupRepository) Update(ctx context.Context, meetup *domain.Meetup, newTagIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, meetup, newTagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockMeetupRepositoryMockRecorder) Update(ctx, meetup, newTagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockMeetupRepository)(nil).Update), ctx, meetup, newTagIDs)
}

// MockchatCacheInvalidator is a mock of chatCacheInvalidator interface.
type MockchatCacheInvalidator struct {
	ctrl     *gomock.Controller
	recorder *MockchatCacheInvalidatorMockRecorder
	isgomock struct{}
}

// MockchatCacheInvalidatorMockRecorder is the mock recorder for MockchatCacheInvalidator.
type MockchatCacheInvalidatorMockRecorder struct {
	mock *MockchatCacheInvalidator
}

// NewMockchatCacheInvalidator creates a new mock instance.
func NewMockchatCacheInvalidator(ctrl *gomock.Controller) *MockchatCacheInvalidator {
	mock := &MockchatCacheInvalidator{ctrl: ctrl}
	mock.recorder = &MockchatCacheInvalidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatCacheInvalidator) EXPECT() *MockchatCacheInvalidatorMockRecorder {
	return m.recorder
}

// InvalidateUserChats mocks base method.
func (m *MockchatCacheInvalidator) InvalidateUserChats(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserChats", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserChats indicates an expected call of InvalidateUserChats.
func (mr *MockchatCacheInvalidatorMockRecorder) InvalidateUserChats(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserChats", reflect.TypeOf((*MockchatCacheInvalidator)(nil).InvalidateUserChats), ctx, userID)
}

// InvalidateUserChatsMany mocks base method.
func (m *MockchatCacheInvalidator) InvalidateUserChatsMany(ctx context.Context, userIDs ...int64) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range userIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InvalidateUserChatsMany", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserChatsMany indicates an expected call of InvalidateUserChatsMany.
func (mr *MockchatCacheInvalidatorMockRecorder) InvalidateUserChatsMany(ctx any, userIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, userIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserChatsMany", reflect.TypeOf((*MockchatCacheInvalidator)(nil).InvalidateUserChatsMany), varargs...)
}

// MockmeetupCache is a mock of meetupCache interface.
type MockmeetupCache struct {
	ctrl     *gomock.Controller
	recorder *MockmeetupCacheMockRecorder
	isgomock struct{}
}

// MockmeetupCacheMockRecorder is the mock recorder for MockmeetupCache.
type MockmeetupCacheMockRecorder struct {
	mock *MockmeetupCache
}

// NewMockmeetupCache creates a new mock instance.
func NewMockmeetupCache(ctrl *gomock.Controller) *MockmeetupCache {
	mock := &MockmeetupCache{ctrl: ctrl}
	mock.recorder = &MockmeetupCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmeetupCache) EXPECT() *MockmeetupCacheMockRecorder {
	return m.recorder
}

// InvalidateMeetup mocks base method.
func (m *MockmeetupCache) InvalidateMeetup(ctx context.Context, meetupID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateMeetup", ctx, meetupID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateMeetup indicates an expected call of InvalidateMeetup.
func (mr *MockmeetupCacheMockRecorder) InvalidateMeetup(ctx, meetupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateMeetup", reflect.TypeOf((*MockmeetupCache)(nil).InvalidateMeetup), ctx, meetupID)
}

// Meetup mocks base method.
func (m *MockmeetupCache) Meetup(ctx context.Context, meetupID, userID int64, load func() (dto.MeetupResponse, []int64, error)) (*dto.MeetupResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Meetup", ctx, meetupID, userID, load)
	ret0, _ := ret[0].(*dto.MeetupResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Meetup indicates an expected call of Meetup.
func (mr *MockmeetupCacheMockRecorder) Meetup(ctx, meetupID, userID, load any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Meetup", reflect.TypeOf((*MockmeetupCache)(nil).Meetup), ctx, meetupID, userID, load)
}
