// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/moderation.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/moderation.go -destination=internal/repo/mocks/moderation_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	repo "github.com/puddingtonnn/offlinemeetup_backend/internal/repo"
	bun "github.com/uptrace/bun"
	gomock "go.uber.org/mock/gomock"
)

// MockReportRepository is a mock of ReportRepository interface.
type MockReportRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReportRepositoryMockRecorder
	isgomock struct{}
}

// MockReportRepositoryMockRecorder is the mock recorder for MockReportRepository.
type MockReportRepositoryMockRecorder struct {
	mock *MockReportRepository
}

// NewMockReportRepository creates a new mock instance.
func NewMockReportRepository(ctrl *gomock.Controller) *MockReportRepository {
	mock := &MockReportRepository{ctrl: ctrl}
	mock.recorder = &MockReportRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportRepository) EXPECT() *MockReportRepositoryMockRecorder {
	return m.recorder
}

// CloseTx mocks base method.
func (m *MockReportRepository) CloseTx(ctx context.Context, tx bun.IDB, id, adminID int64, status domain.ReportStatus, resolution string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseTx", ctx, tx, id, adminID, status, resolution)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseTx indicates an expected call of CloseTx.
func (mr *MockReportRepositoryMockRecorder) CloseTx(ctx, tx, id, adminID, status, resolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseTx", reflect.TypeOf((*MockReportRepository)(nil).CloseTx), ctx, tx, id, adminID, status, resolution)
}

// GetByID mocks base method.
func (m *MockReportRepository) GetByID(ctx context.Context, id int64) (*domain.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockReportRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockReportRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockReportRepository) List(ctx context.Context, q repo.ReportQuery) ([]domain.Report, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, q)
	ret0, _ := ret[0].([]domain.Report)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockReportRepositoryMockRecorder) List(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReportRepository)(nil).List), ctx, q)
}

// ResolveTargetTx mocks base method.
func (m *MockReportRepository) ResolveTargetTx(ctx context.Context, tx bun.IDB, targetType domain.ReportTargetType, targetID, adminID int64, resolution string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTargetTx", ctx, tx, targetType, targetID, adminID, resolution)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTargetTx indicates an expected call of ResolveTargetTx.
func (mr *MockReportRepositoryMockRecorder) ResolveTargetTx(ctx, tx, targetType, targetID, adminID, resolution any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTargetTx", reflect.TypeOf((*MockReportRepository)(nil).ResolveTargetTx), ctx, tx, targetType, targetID, adminID, resolution)
}

// RunInTx mocks base method.
func (m *MockReportRepository) RunInTx(ctx context.Context, fn func(bun.Tx) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockReportRepositoryMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockReportRepository)(nil).RunInTx), ctx, fn)
}

// MockModerationMeetupRepository is a mock of ModerationMeetupRepository interface.
type MockModerationMeetupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockModerationMeetupRepositoryMockRecorder
	isgomock struct{}
}

// MockModerationMeetupRepositoryMockRecorder is the mock recorder for MockModerationMeetupRepository.
type MockModerationMeetupRepositoryMockRecorder struct {
	mock *MockModerationMeetupRepository
}

// NewMockModerationMeetupRepository creates a new mock instance.
func NewMockModerationMeetupRepository(ctrl *gomock.Controller) *MockModerationMeetupRepository {
	mock := &MockModerationMeetupRepository{ctrl: ctrl}
	mock.recorder = &MockModerationMeetupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModerationMeetupRepository) EXPECT() *MockModerationMeetupRepositoryMockRecorder {
	return m.recorder
}

// CancelTx mocks base method.
func (m *MockModerationMeetupRepository) CancelTx(ctx context.Context, tx bun.IDB, meetupID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelTx", ctx, tx, meetupID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelTx indicates an expected call of CancelTx.
func (mr *MockModerationMeetupRepositoryMockRecorder) CancelTx(ctx, tx, meetupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelTx", reflect.TypeOf((*MockModerationMeetupRepository)(nil).CancelTx), ctx, tx, meetupID)
}

// GetByID mocks base method.
func (m *MockModerationMeetupRepository) GetByID(ctx context.Context, id, currentUserID int64) (*domain.Meetup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, currentUserID)
	ret0, _ := ret[0].(*domain.Meetup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockModerationMeetupRepositoryMockRecorder) GetByID(ctx, id, currentUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockModerationMeetupRepository)(nil).GetByID), ctx, id, currentUserID)
}

// MockModerationChatRepository is a mock of ModerationChatRepository interface.
type MockModerationChatRepository struct {
	ctrl     *gomock.Controller
	recorder *MockModerationChatRepositoryMockRecorder
	isgomock struct{}
}

// MockModerationChatRepositoryMockRecorder is the mock recorder for MockModerationChatRepository.
type MockModerationChatRepositoryMockRecorder struct {
	mock *MockModerationChatRepository
}

// NewMockModerationChatRepository creates a new mock instance.
func NewMockModerationChatRepository(ctrl *gomock.Controller) *MockModerationChatRepository {
	mock := &MockModerationChatRepository{ctrl: ctrl}
	mock.recorder = &MockModerationChatRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModerationChatRepository) EXPECT() *MockModerationChatRepositoryMockRecorder {
	return m.recorder
}

// DeleteMessageByAdminTx mocks base method.
func (m *MockModerationChatRepository) DeleteMessageByAdminTx(ctx context.Context, tx bun.IDB, msgID int64) (*repo.DeletedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessageByAdminTx", ctx, tx, msgID)
	ret0, _ := ret[0].(*repo.DeletedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMessageByAdminTx indicates an expected call of DeleteMessageByAdminTx.
func (mr *MockModerationChatRepositoryMockRecorder) DeleteMessageByAdminTx(ctx, tx, msgID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessageByAdminTx", reflect.TypeOf((*MockModerationChatRepository)(nil).DeleteMessageByAdminTx), ctx, tx, msgID)
}

// MockModerationProfileRepository is a mock of ModerationProfileRepository interface.
type MockModerationProfileRepository struct {
	ctrl     *gomock.Controller
	recorder *MockModerationProfileRepositoryMockRecorder
	isgomock struct{}
}

// MockModerationProfileRepositoryMockRecorder is the mock recorder for MockModerationProfileRepository.
type MockModerationProfileRepositoryMockRecorder struct {
	mock *MockModerationProfileRepository
}

// NewMockModerationProfileRepository creates a new mock instance.
func NewMockModerationProfileRepository(ctrl *gomock.Controller) *MockModerationProfileRepository {
	mock := &MockModerationProfileRepository{ctrl: ctrl}
	mock.recorder = &MockModerationProfileRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockModerationProfileRepository) EXPECT() *MockModerationProfileRepositoryMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockModerationProfileRepository) GetByUserID(ctx context.Context, userID int64) (*domain.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockModerationProfileRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockModerationProfileRepository)(nil).GetByUserID), ctx, userID)
}

// MockUserMeetupLister is a mock of UserMeetupLister interface.
type MockUserMeetupLister struct {
	ctrl     *gomock.Controller
	recorder *MockUserMeetupListerMockRecorder
	isgomock struct{}
}

// MockUserMeetupListerMockRecorder is the mock recorder for MockUserMeetupLister.
type MockUserMeetupListerMockRecorder struct {
	mock *MockUserMeetupLister
}

// NewMockUserMeetupLister creates a new mock instance.
func NewMockUserMeetupLister(ctrl *gomock.Controller) *MockUserMeetupLister {
	mock := &MockUserMeetupLister{ctrl: ctrl}
	mock.recorder = &MockUserMeetupListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserMeetupLister) EXPECT() *MockUserMeetupListerMockRecorder {
	return m.recorder
}

// MeetupIDsForUser mocks base method.
func (m *MockUserMeetupLister) MeetupIDsForUser(ctx context.Context, userID int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MeetupIDsForUser", ctx, userID)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MeetupIDsForUser indicates an expected call of MeetupIDsForUser.
func (mr *MockUserMeetupListerMockRecorder) MeetupIDsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MeetupIDsForUser", reflect.TypeOf((*MockUserMeetupLister)(nil).MeetupIDsForUser), ctx, userID)
}
