// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/report.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/report.go -destination=internal/repo/mocks/report_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockReportCreator is a mock of ReportCreator interface.
type MockReportCreator struct {
	ctrl     *gomock.Controller
	recorder *MockReportCreatorMockRecorder
	isgomock struct{}
}

// MockReportCreatorMockRecorder is the mock recorder for MockReportCreator.
type MockReportCreatorMockRecorder struct {
	mock *MockReportCreator
}

// NewMockReportCreator creates a new mock instance.
func NewMockReportCreator(ctrl *gomock.Controller) *MockReportCreator {
	mock := &MockReportCreator{ctrl: ctrl}
	mock.recorder = &MockReportCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportCreator) EXPECT() *MockReportCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReportCreator) Create(ctx context.Context, rep *domain.Report) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, rep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReportCreatorMockRecorder) Create(ctx, rep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReportCreator)(nil).Create), ctx, rep)
}
