// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/tag.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/tag.go -destination=internal/service/mocks/tag_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/puddingtonnn/offlinemeetup_backend/internal/domain"
	dto "github.com/puddingtonnn/offlinemeetup_backend/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockTagRepository is a mock of TagRepository interface.
type MockTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagRepositoryMockRecorder
	isgomock struct{}
}

// MockTagRepositoryMockRecorder is the mock recorder for MockTagRepository.
type MockTagRepositoryMockRecorder struct {
	mock *MockTagRepository
}

// NewMockTagRepository creates a new mock instance.
func NewMockTagRepository(ctrl *gomock.Controller) *MockTagRepository {
	mock := &MockTagRepository{ctrl: ctrl}
	mock.recorder = &MockTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagRepository) EXPECT() *MockTagRepositoryMockRecorder {
	return m.recorder
}

// ListVisible mocks base method.
func (m *MockTagRepository) ListVisible(ctx context.Context) ([]domain.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVisible", ctx)
	ret0, _ := ret[0].([]domain.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVisible indicates an expected call of ListVisible.
func (mr *MockTagRepositoryMockRecorder) ListVisible(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVisible", reflect.TypeOf((*MockTagRepository)(nil).ListVisible), ctx)
}

// MocktagCache is a mock of tagCache interface.
type MocktagCache struct {
	ctrl     *gomock.Controller
	recorder *MocktagCacheMockRecorder
	isgomock struct{}
}

// MocktagCacheMockRecorder is the mock recorder for MocktagCache.
type MocktagCacheMockRecorder struct {
	mock *MocktagCache
}

// NewMocktagCache creates a new mock instance.
func NewMocktagCache(ctrl *gomock.Controller) *MocktagCache {
	mock := &MocktagCache{ctrl: ctrl}
	mock.recorder = &MocktagCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktagCache) EXPECT() *MocktagCacheMockRecorder {
	return m.recorder
}

// ListTags mocks base method.
func (m *MocktagCache) ListTags(ctx context.Context, load func() ([]dto.TagResponse, error)) ([]dto.TagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx, load)
	ret0, _ := ret[0].([]dto.TagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MocktagCacheMockRecorder) ListTags(ctx, load any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MocktagCache)(nil).ListTags), ctx, load)
}
